version: "3"

services:
  web:
    build:
      context: .
    ports:
      - "1775:1775"
    container_name: ems_web
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_USER=user_
      - MYSQL_PASSWORD=userone
      - MYSQL_ROOT_PASSWORD=secret_pw
      - MYSQL_HOST=db
      - CELERY_BROKER=redis://redis:6379/0
    depends_on:
      - db
      - redis_db
    restart: always
    networks:
      - ems_web_net
    volumes:
      - .:/ems_web
    expose:
      - "1775"
    command: >
      sh -c "python manage.py collectstatic --no-input && python manage.py migrate && python manage.py createsuperuser_if_none_exists && python manage.py runserver 0.0.0.0:1775"

  db:
    build:
      context: .
      dockerfile: ./Dockerfile_mysql
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_USER=user_
      - MYSQL_PASSWORD=userone
      - MYSQL_ROOT_PASSWORD=secret_pw
      - MYSQL_HOST=db
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    expose:
      - "3306"
    restart: on-failure
    command: --default-authentication-plugin=mysql_native_password
    volumes:
    - ems_web_db_data:/var/lib/mysql
    networks:
      - ems_web_net

  redis_db:
    container_name: redis
    hostname: redis
    image: redis:latest
    networks:
      - ems_web_net
    expose:
      - "6379"
    restart: on-failure

  celery:
    build: .
    user: nobody
    command: celery -A ems worker -l INFO
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_USER=user_
      - MYSQL_PASSWORD=userone
      - MYSQL_ROOT_PASSWORD=secret_pw
      - MYSQL_HOST=db
      - CELERY_BROKER=redis://redis:6379/0
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
      - redis_db
    networks:
      - ems_web_net
    restart: on-failure

networks:
  ems_web_net:
    driver: bridge

volumes:
  ems_web_db_data: